### ISSUE TITLE
Create Simple Programs

### ISSUE THREAD

**Issue by ag3n7** [FOSS-GCEK/Hacktoberfest#6]
# Create Simple Programs

Create programs for simple calculations :

1. Addition
2. Subtraction

```
Try different programming languages
```

**Comment by pawki07** [comment]
Hey, I would like to claim this issue. Please assign it to me.

**Comment by Mahendra7985** [comment]
hey i would like to work on this

**Comment by kaushambisharma** [comment]
I would like to contribute.

**Comment by abhinand-c** [comment]
You all can work on it and create a pull request to contribute your works.

**Comment by abhinand-c** [comment]
> Hey, I would like to claim this issue. Please assign it to me.

You can work on it, and create a PR. This is a general guidelines issue for beginners in GitHub, to contribute to. It shall remain open till hacktoctober fest, or till it deems fit.
There's no need for anyone to claim this issue.
